#file: noinspection SpringBootApplicationYaml
# -> this is for suppressing `config-server configuration` warning
server:
  port: 8081

spring:
  application:
    name: 4-AUTHENTICATION-SERVICE
---

#config-server configuration
spring:
  config:
    import: optional:${CONFIG_SERVER_URI:http://localhost:9296}/
---

#custom variables
token:
  secret:
    key: "k9i9rTPqCxyV8mA6nDbM1d1bqAV4j8OZpA6OyUzE1k5f6Hj3i5Ra3kMIEsFuXL9vbnfEQglXqFJopHsA7kqJpQ=="
  prefix: "Bearer "

account:
  verification:
    auth:
      url: "http://localhost:8085" # Frontend base URL for verification link

file:
  upload:
    profiles:
      directory: "./uploads/profile_pictures" 
---

#mysql-db configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_AUTHENTICATION_NAME:hive_authentication_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Outlook2@@3}
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 890f1e6e3785be
    password: 960854ef9e93d7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: WARN
    org.springframework: WARN